/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import javax.swing.JFrame;

/**
 *
 * @author Alek
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        meniStan = new javax.swing.JMenu();
        miDodajStan = new javax.swing.JMenuItem();
        miPretraziStanove = new javax.swing.JMenuItem();
        meniKlijent = new javax.swing.JMenu();
        miDodajKlijenta = new javax.swing.JMenuItem();
        miPretraziKlijente = new javax.swing.JMenuItem();
        meniPotvrda = new javax.swing.JMenu();
        miKreirajPotvrdu = new javax.swing.JMenuItem();
        miPretraziPotvrde = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meniStan.setText("Stan");

        miDodajStan.setText("Dodaj novi");
        miDodajStan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajStanActionPerformed(evt);
            }
        });
        meniStan.add(miDodajStan);

        miPretraziStanove.setText("Pretrazi stanove");
        miPretraziStanove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziStanoveActionPerformed(evt);
            }
        });
        meniStan.add(miPretraziStanove);

        jMenuBar1.add(meniStan);

        meniKlijent.setText("Klijent");

        miDodajKlijenta.setText("Dodaj klijenta");
        miDodajKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDodajKlijentaActionPerformed(evt);
            }
        });
        meniKlijent.add(miDodajKlijenta);

        miPretraziKlijente.setText("Pretrazi klijente");
        miPretraziKlijente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziKlijenteActionPerformed(evt);
            }
        });
        meniKlijent.add(miPretraziKlijente);

        jMenuBar1.add(meniKlijent);

        meniPotvrda.setText("Potvrda");

        miKreirajPotvrdu.setText("Kreiraj potvrdu");
        miKreirajPotvrdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajPotvrduActionPerformed(evt);
            }
        });
        meniPotvrda.add(miKreirajPotvrdu);

        miPretraziPotvrde.setText("Pretrazi potvrde");
        miPretraziPotvrde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziPotvrdeActionPerformed(evt);
            }
        });
        meniPotvrda.add(miPretraziPotvrde);

        jMenuBar1.add(meniPotvrda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDodajStanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajStanActionPerformed
        new FrmNoviStan(this, true).setVisible(true);
    }//GEN-LAST:event_miDodajStanActionPerformed

    private void miPretraziStanoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziStanoveActionPerformed
        new FrmPretragaStanova(this, true).setVisible(true);
    }//GEN-LAST:event_miPretraziStanoveActionPerformed

    private void miDodajKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDodajKlijentaActionPerformed
        new FrmNoviKlijent(this, true).setVisible(true);
    }//GEN-LAST:event_miDodajKlijentaActionPerformed

    private void miPretraziKlijenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziKlijenteActionPerformed
        new FrmPretragaKlijenata(this, true).setVisible(true);
    }//GEN-LAST:event_miPretraziKlijenteActionPerformed

    private void miKreirajPotvrduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajPotvrduActionPerformed
        new FrmKreirajPotvrdu(this, true).setVisible(true);
    }//GEN-LAST:event_miKreirajPotvrduActionPerformed

    private void miPretraziPotvrdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziPotvrdeActionPerformed
        new FrmPretragaPotvrda(this, true).setVisible(true);
    }//GEN-LAST:event_miPretraziPotvrdeActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu meniKlijent;
    private javax.swing.JMenu meniPotvrda;
    private javax.swing.JMenu meniStan;
    private javax.swing.JMenuItem miDodajKlijenta;
    private javax.swing.JMenuItem miDodajStan;
    private javax.swing.JMenuItem miKreirajPotvrdu;
    private javax.swing.JMenuItem miPretraziKlijente;
    private javax.swing.JMenuItem miPretraziPotvrde;
    private javax.swing.JMenuItem miPretraziStanove;
    // End of variables declaration//GEN-END:variables
}
