/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form;

import domen.Lokacija;
import domen.Stan;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author Alek
 */
public class FrmIzmenaStana extends javax.swing.JDialog {

    private Stan stan;

    /**
     * Creates new form FrmIzmenaStana
     */
    public FrmIzmenaStana(java.awt.Frame parent, boolean modal, Stan stan) {
        super(parent, modal);
        initComponents();
        this.stan = stan;
        setLocationRelativeTo(parent);
        try {
            srediFormu();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error in view initialization: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStanID = new javax.swing.JLabel();
        txtStanID = new javax.swing.JTextField();
        lblKvadratura = new javax.swing.JLabel();
        txtKvadratura = new javax.swing.JTextField();
        txtBrSoba = new javax.swing.JTextField();
        lblBrSoba = new javax.swing.JLabel();
        lblSprat = new javax.swing.JLabel();
        txtSprat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbLokacija = new javax.swing.JComboBox();
        btnIzmeni = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        lblErrorKvadratura = new javax.swing.JLabel();
        lblErrorBrojSoba = new javax.swing.JLabel();
        lblErrorSprat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmena stana");

        lblStanID.setText("ID:");

        txtStanID.setEditable(false);

        lblKvadratura.setText("Kvadratura:");

        lblBrSoba.setText("Broj soba:");

        lblSprat.setText("Sprat:");

        jLabel1.setText("Lokacija:");

        cmbLokacija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        lblErrorKvadratura.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorKvadratura.setText("jLabel2");

        lblErrorBrojSoba.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorBrojSoba.setText("jLabel2");

        lblErrorSprat.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorSprat.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOdustani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorKvadratura, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStanID, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStanID, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKvadratura, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKvadratura, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorBrojSoba, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBrSoba, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBrSoba, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSprat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSprat, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblErrorSprat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStanID)
                    .addComponent(txtStanID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKvadratura)
                    .addComponent(txtKvadratura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorKvadratura)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrSoba)
                    .addComponent(txtBrSoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorBrojSoba)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSprat)
                    .addComponent(txtSprat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorSprat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbLokacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOdustani)
                    .addComponent(btnIzmeni))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if (validateForm()) {
            return;
        }
        stan.setKvadratura(Double.parseDouble(txtKvadratura.getText().trim()));
        stan.setBrojSoba(Integer.parseInt(txtBrSoba.getText().trim()));
        stan.setSprat(Integer.parseInt(txtSprat.getText().trim()));
        stan.setLokacija((Lokacija) cmbLokacija.getSelectedItem());

        try {
            Kontroler.getInstance().izmeniStan(stan);
            JOptionPane.showMessageDialog(this, "Stan je uspesno izmenjen!");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JComboBox cmbLokacija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBrSoba;
    private javax.swing.JLabel lblErrorBrojSoba;
    private javax.swing.JLabel lblErrorKvadratura;
    private javax.swing.JLabel lblErrorSprat;
    private javax.swing.JLabel lblKvadratura;
    private javax.swing.JLabel lblSprat;
    private javax.swing.JLabel lblStanID;
    private javax.swing.JTextField txtBrSoba;
    private javax.swing.JTextField txtKvadratura;
    private javax.swing.JTextField txtSprat;
    private javax.swing.JTextField txtStanID;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws Exception {
        txtStanID.setText(String.valueOf(stan.getStanID()));
        txtKvadratura.setText(String.valueOf(stan.getKvadratura()));
        txtBrSoba.setText(String.valueOf(stan.getBrojSoba()));
        txtSprat.setText(String.valueOf(stan.getSprat()));

        lblErrorBrojSoba.setVisible(false);
        lblErrorKvadratura.setVisible(false);
        lblErrorSprat.setVisible(false);

        popuniCombo();

        cmbLokacija.setSelectedItem(stan.getLokacija());
    }

    private void popuniCombo() throws Exception {
        cmbLokacija.removeAllItems();

        List<Lokacija> lokacije = Kontroler.getInstance().getLokacije();
        for (Lokacija lokacija : lokacije) {
            cmbLokacija.addItem(lokacija);
        }

    }

    private boolean validateForm() {
        boolean flag = false;
        if (txtKvadratura.getText().trim().isEmpty()) {
            flag = true;
            lblErrorKvadratura.setText("Morate uneti kvadraturu stana!");
            lblErrorKvadratura.setVisible(true);
        }
        if (txtBrSoba.getText().trim().isEmpty()) {
            flag = true;
            lblErrorBrojSoba.setText("Morate uneti broj soba stana!");
            lblErrorBrojSoba.setVisible(true);
        }
        if (txtSprat.getText().trim().isEmpty()) {
            flag = true;
            lblErrorSprat.setText("Morate uneti sprat stana!");
            lblErrorSprat.setVisible(true);
        }

        return flag;
    }

}
