/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form;


import domen.Klijent;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author Alek
 */
public class FrmNoviKlijent extends javax.swing.JDialog {

    /**
     * Creates new form FrmNoviKlijent
     */
    public FrmNoviKlijent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        try {
            srediFormu();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error in view initialization: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJMBG = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();
        lblErrorJMBG = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        lblErrorIme = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        lblPrezime = new javax.swing.JLabel();
        lblErrorPrezime = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblAdresa = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        lblErrorAdresa = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj klijenta");

        lblJMBG.setText("JMBG:");

        lblErrorJMBG.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorJMBG.setText("jLabel1");

        lblIme.setText("Ime:");

        lblErrorIme.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorIme.setText("jLabel1");

        lblPrezime.setText("Prezime:");

        lblErrorPrezime.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPrezime.setText("jLabel1");

        lblemail.setText("E-mail:");

        lblErrorEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorEmail.setText("jLabel1");

        lblAdresa.setText("Adresa:");

        lblErrorAdresa.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorAdresa.setText("jLabel1");

        btnDodaj.setText("Dodaj klijenta");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDodaj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblErrorJMBG)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblErrorIme)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblErrorPrezime)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblErrorEmail)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblErrorAdresa)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJMBG)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorJMBG)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorIme)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorPrezime)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorEmail)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdresa)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorAdresa)
                .addGap(18, 18, 18)
                .addComponent(btnDodaj)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        try{
            if(validateForm()){
                return;
            }
            Klijent klijent = new Klijent();
            
            klijent.setJMBG(txtJMBG.getText().trim());
            klijent.setIme(txtIme.getText().trim());
            klijent.setPrezime(txtPrezime.getText().trim());
            klijent.setEmail(txtEmail.getText().trim());
            klijent.setAdresa(txtAdresa.getText().trim());
            
            Kontroler.getInstance().dodajKlijenta(klijent);
            
            JOptionPane.showMessageDialog(this, "Klijent uspesno dodat!");
            txtJMBG.setText("");
            txtIme.setText("");
            txtPrezime.setText("");
            txtEmail.setText("");
            txtAdresa.setText("");
            lblErrorJMBG.setVisible(false);
            lblErrorIme.setVisible(false);
            lblErrorPrezime.setVisible(false);
            lblErrorAdresa.setVisible(false);
            lblErrorEmail.setVisible(false);
        } catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greska: \n" + ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblErrorAdresa;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorIme;
    private javax.swing.JLabel lblErrorJMBG;
    private javax.swing.JLabel lblErrorPrezime;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblJMBG;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JLabel lblemail;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private boolean validateForm() {
        boolean flag = false;
        if(txtJMBG.getText().trim().isEmpty()){
            flag = true;
            lblErrorJMBG.setText("Morate uneti JMBG klijenta!");
            lblErrorJMBG.setVisible(true);
        }
        
        if(txtIme.getText().trim().isEmpty()){
            flag = true;
            lblErrorIme.setText("Morate uneti ime klijenta!");
            lblErrorIme.setVisible(true);
        }
        
        if(txtPrezime.getText().trim().isEmpty()){
            flag = true;
            lblErrorPrezime.setText("Morate uneti prezime klijenta!");
            lblErrorPrezime.setVisible(true);
        }
        
        if(txtEmail.getText().trim().isEmpty()){
            flag = true;
            lblErrorEmail.setText("Morate uneti e-mail klijenta!");
            lblErrorEmail.setVisible(true);
        }
        
        if(txtAdresa.getText().trim().isEmpty()){
            flag = true;
            lblErrorAdresa.setText("Morate uneti adresu klijenta!");
            lblErrorAdresa.setVisible(true);
        }
        
        
        return flag;
    }

    private void srediFormu() {
        lblErrorJMBG.setVisible(false);
        lblErrorIme.setVisible(false);
        lblErrorPrezime.setVisible(false);
        lblErrorEmail.setVisible(false);
        lblErrorAdresa.setVisible(false);
    }
}
